"""Generate and post PR review comments from findings."""

import argparse
import json
import subprocess
import sys


def format_findings(findings: list[dict]) -> str:
    """Format findings into a markdown PR comment."""
    if not findings:
        return (
            "## Lotus Vision QA Report\n\n"
            "No issues found. The application passed visual QA testing."
        )

    lines = [
        "## Lotus Vision QA Report\n",
        "Visual QA testing found the following issues:\n",
    ]

    for i, finding in enumerate(findings, 1):
        persona = finding.get("persona", "Unknown")
        text = finding.get("text", "")
        finding_type = finding.get("type", "finding")

        if finding_type == "summary":
            # Clean up the DONE marker from summaries
            text = text.replace("DONE", "").strip()
            lines.append(f"### {persona}\n")
            lines.append(f"{text}\n")
        else:
            lines.append(f"**{i}.** {text}\n")

    lines.append("\n---\n")
    lines.append("*Generated by [Lotus Vision](https://github.com/your-org/lotus-vision)*")

    return "\n".join(lines)


def post_comment(repo: str, pr_number: str, body: str) -> None:
    """Post a comment on a GitHub PR using gh CLI."""
    result = subprocess.run(
        [
            "gh", "pr", "comment", pr_number,
            "--repo", repo,
            "--body", body,
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"Failed to post comment: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    print(f"Posted review comment on PR #{pr_number}")


def main():
    parser = argparse.ArgumentParser(description="Post Lotus Vision findings to a PR")
    parser.add_argument("--findings", required=True, help="Path to findings JSON")
    parser.add_argument("--repo", required=True, help="GitHub repo (owner/name)")
    parser.add_argument("--pr", required=True, help="PR number")

    args = parser.parse_args()

    with open(args.findings) as f:
        findings = json.load(f)

    body = format_findings(findings)
    post_comment(args.repo, args.pr, body)


if __name__ == "__main__":
    main()
